### PR TITLE
Improve MsgPack Serialization: Delegate Support, List Fixes, and Byte Array Handling

### LINKED ISSUE #2571: [MonoV2] Event listeners with a byte[] as a parameter fail to register
### What happened?

Events that take byte arrays as a parameter fail when registering (past build 8380).

```csharp
public class ExampleServerScript : BaseScript
{
	[EventHandler("exampleEvent", Binding.Remote)]
	private static void HandleIncomingRequest([Source] Player player, byte[] data)
	{
		Debug.WriteLine("Hello World");
	}
}
```

```
[rcon/script:Placehol] Registering CitizenFX.Core.EventHandler PlaceholderRP.Server.Hooks.Hooks.HandleIncomingRequest failed with exception: System.ArgumentException: Bad type def, can't handle '>' at 28
[rcon/script:Placehol] Parameter name: typeName
[rcon/script:Placehol]   at System.TypeSpec.Parse (System.String name, System.Int32& p, System.Boolean is_recurse, System.Boolean allow_aqn) [0x004f5] in <fbc4ec45371543bfba3678ebb82caf6d>:0
[rcon/script:Placehol]   at System.TypeSpec.Parse (System.String typeName) [0x00010] in <fbc4ec45371543bfba3678ebb82caf6d>:0
[rcon/script:Placehol]   at System.Reflection.Emit.ModuleBuilder.GetType (System.String className, System.Boolean throwOnError, System.Boolean ignoreCase) [0x00037] in <fbc4ec45371543bfba3678ebb82caf6d>:0
[rcon/script:Placehol]   at System.Reflection.Emit.ModuleBuilder.GetType (System.String className) [0x00000] in <fbc4ec45371543bfba3678ebb82caf6d>:0
[rcon/script:Placehol]   at CitizenFX.MsgPack.Formatters.ArrayFormatter.Build (System.Type type, System.Type typeArray) [0x00016] in C:\gl\builds\cfx-fivem\master\fxserver\vendor\msgpack-cs\MsgPack\Formatters\ArrayFormatter.cs:17
[rcon/script:Placehol]   at CitizenFX.MsgPack.MsgPackRegistry.CreateSerializer (System.Type type) [0x0002a] in C:\gl\builds\cfx-fivem\master\fxserver\vendor\msgpack-cs\MsgPack\MsgPackRegistry.cs:190
[rcon/script:Placehol]   at CitizenFX.MsgPack.MsgPackRegistry.GetOrCreateDeserializer (System.Type type) [0x00000] in C:\gl\builds\cfx-fivem\master\fxserver\vendor\msgpack-cs\MsgPack\MsgPackRegistry.cs:174
[rcon/script:Placehol]   at CitizenFX.MsgPack.MsgPackDeserializer.ConstructDelegate (System.Object target, System.Reflection.MethodInfo method) [0x0022b] in C:\gl\builds\cfx-fivem\master\fxserver\vendor\msgpack-cs\MsgPack\MsgPackFunc.cs:124
[rcon/script:Placehol]   at CitizenFX.MsgPack.MsgPackDeserializer.CreateDelegate (System.Object target, System.Reflection.MethodInfo method) [0x000a0] in C:\gl\builds\cfx-fivem\master\fxserver\vendor\msgpack-cs\MsgPack\MsgPackFunc.cs:39
[rcon/script:Placehol]   at CitizenFX.Core.BaseScript.Initialize () [0x000a4] in C:\gl\builds\cfx-fivem\master\fxserver\code\client\clrcore-v2\BaseScript.cs:97
[rcon/script:Placehol] Instantiated instance of script PlaceholderRP.Server.AdminQOL.AdminCommands.
```

### Expected result

Event should not fail to register

### Reproduction steps

1. Use build 8385 of FxServer

2. Make a resource that uses MonoV2

3. Add this script to your resource and watch the server/client fail to register it

```csharp
public class ExampleServerScript : BaseScript
{
	[EventHandler("exampleEvent", Binding.Remote)]
	private static void HandleIncomingRequest(Player player, byte[] data)
	{
		Debug.WriteLine("Hello World");
	}
}
```

### Importancy

Slight inconvenience

### Area(s)

ScRT: C#

### Specific version(s)

Server 8380 Windows

### Additional information

_No response_

### LINKED ISSUE #2613: [MonoV2] Receiving events above 256 bytes leads to ArgumentException in MsgPackDeserializer
### What happened?

Receiving an Event with a string grater than 256 bytes leads to ``System.ArgumentException`` within ``MsgPackDeserializer``

Full error:
```
[  18754843] [b2699_GTAProce]             MainThrd/ System.ArgumentException: MsgPackDeserializer tried to retrieve 321 bytes while only 256 bytes remain
[  18754843] [b2699_GTAProce]             MainThrd/   at CitizenFX.MsgPack.MsgPackDeserializer.AdvancePointer (System.UInt32 amount) [0x0005d] in C:\gl\builds\cfx-fivem\master\fivem\vendor\msgpack-cs\MsgPack\MsgPackDeserializer.cs:394 
[  18754843] [b2699_GTAProce]             MainThrd/   at CitizenFX.MsgPack.MsgPackDeserializer.DeserializeAsString () [0x001de] in C:\gl\builds\cfx-fivem\master\fivem\vendor\msgpack-cs\MsgPack\MsgPackDeserializerConvert.cs:559 
[  18754843] [b2699_GTAProce]             MainThrd/   at (wrapper dynamic-method) System.Object:GCClient.ModusControl.ModusController.JoinMode (object,CitizenFX.Core.Remote,CitizenFX.MsgPack.MsgPackDeserializer&)
[  18754843] [b2699_GTAProce]             MainThrd/   at CitizenFX.Core.EventsManager.IncomingEvent (System.String eventName, System.String sourceString, CitizenFX.Core.Binding origin, System.Byte* argsSerialized, System.Int32 serializedSize) [0x00050] in C:\gl\builds\cfx-fivem\master\fivem\code\client\clrcore-v2\Interop\EventsManager.cs:34 
```

### Expected result

string deserialized without issue

### Reproduction steps

```cs
public class ReproScriptServer : BaseScript {
    [EventHandler("playerJoining")]
    private void OnPlayerJoining([Source] Player player, string oldId) {
        player.TriggerEvent("SendString", new string('A', 256) + "B");
    }
}

public class ReproScriptClient : BaseScript {
    [EventHandler("SendString")]
    public void JoinMode(string stringValue) {
        Debug.WriteLine($"Succesfully received: {stringValue}");
    }
}
```

### Importancy

Crash

### Area(s)

FiveM, Natives, ScRT: C#

### Specific version(s)

Version: FXServer-master v1.0.0.8780 linux with OneSync enabled

### Additional information

_No response_

### LINKED ISSUE #2653: C# Export Server Crash 8978+
### What happened?

Invoking an export from C# results in a server crash.
```c#
Exports["c_sharp"].csharp("from c#");
```

### Expected result

export should be executed

### Reproduction steps

Invoke an export from with in a C# server script dll
Exports worked in 8965 
Exports do not work in 8978, 8981

```c#
using System;
using System.Threading.Tasks;

using CitizenFX.Core;
using static CitizenFX.Core.Native.API;

namespace c_sharp
{
  public class C_Sharp : BaseScript
  {
    public static C_Sharp Self { get; private set; }

    public C_Sharp()
    {
      Self = this;
    }

    private void CSharp(string text)
    {
      Console.WriteLine($"c# {text}");
    }

    [EventHandler("onResourceStart")]
    private void OnResourceStart(string resourceName)
    {
      if (GetCurrentResourceName() == resourceName)
      {
        Exports.Add("csharp", (Action<string>)CSharp);
        Console.WriteLine("invoke c# export from c#");
        Exports["c_sharp"].csharp("from c#");
      }
    }
  }
}
```

### Importancy

Crash

### Area(s)

FXServer

### Specific version(s)

Server 8978

### Additional information

```
=================================================================
        Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
        Managed Stacktrace:
=================================================================
          at <unknown> <0xffffffff>
          at CitizenFX.Core.GameInterface:InvokeFunctionReference <0x000bc>
          at CitizenFX.Core.RemoteFunctionReference:_InvokeNative <0x000ba>
          at CitizenFX.Core.RemoteFunctionReference:InvokeNative <0x0004a>
          at <>c__DisplayClass36_0:<CreateRemoteFunctionReference>b__0 <0x00092>
          at <Module>:runtime_invoke_object__this___object <0x0013f>
          at <unknown> <0xffffffff>
          at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x000a2>
          at System.Reflection.RuntimeMethodInfo:Invoke <0x00162>
          at System.Reflection.MethodBase:Invoke <0x0006b>
          at System.Delegate:DynamicInvokeImpl <0x00402>
          at System.MulticastDelegate:DynamicInvokeImpl <0x0006a>
          at System.Delegate:DynamicInvoke <0x0004b>
          at CitizenFX.Core.ExportDictionary:Invoke <0x0014a>
          at CitizenFX.Core.InternalManager:TriggerEvent <0x0086a>
          at CitizenFX.Core.InternalManager:TriggerEvent <0x000d2>
          at CitizenFX.Core.InternalManager:TriggerEvent <0x002e2>
          at CitizenFX.Core.InternalManager:TriggerEvent <0x001a0>
          at CitizenFX.Core.InternalManager:TriggerEvent <0x00092>
          at CitizenFX.Core.MonoScriptRuntime:TriggerEvent <0x000a2>
          at CitizenFX.Core.IScriptEventRuntime:TriggerEvent <0x0008b>
          at CitizenFX.Core.IScriptEventRuntime:TriggerEvent <0x00132>
          at <unknown> <0xffffffff>
          at WrapScriptHost:InvokeNative <0x001f2>
          at WrapScriptHost:InvokeNative <0x00209>
          at CitizenFX.Core.ScriptContext:InvokeInternal <0x00084>
          at CitizenFX.Core.ScriptContext:InvokeInternal <0x000ea>
          at CitizenFX.Core.ScriptContext:Invoke <0x0004a>
          at CitizenFX.Core.Native.Function:InvokeInternal <0x000fa>
          at CitizenFX.Core.Native.Function:Call <0x00052>
          at CitizenFX.Core.BaseScript:TriggerEventInternal <0x00302>
          at CitizenFX.Core.BaseScript:TriggerEvent <0x00062>
          at CitizenFX.Core.ExportSet:TryInvokeMember <0x001f2>
          at System.Object:CallSite.Target <0x001f2>
          at System.Dynamic.UpdateDelegates:UpdateAndExecuteVoid2 <0x0081c>
          at com.twitchrp.log.C_Sharp:OnResourceStart <0x002da>
          at <Module>:runtime_invoke_void__this___object <0x00137>
          at <unknown> <0xffffffff>
          at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x000a2>
          at System.Reflection.RuntimeMethodInfo:Invoke <0x00162>
          at System.Reflection.MethodBase:Invoke <0x0006b>
          at System.Delegate:DynamicInvokeImpl <0x00402>
          at System.MulticastDelegate:DynamicInvokeImpl <0x0006a>
          at System.Delegate:DynamicInvoke <0x0004b>
          at <Invoke>d__5:MoveNext <0x0026a>
          at System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start <0x000ea>
          at CitizenFX.Core.EventHandlerEntry:Invoke <0x001a2>
          at <Invoke>d__5:MoveNext <0x0018a>
          at System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start <0x00102>
          at CitizenFX.Core.EventHandlerDictionary:Invoke <0x001da>
          at <>c__DisplayClass38_2:<TriggerEvent>b__0 <0x0017a>
          at System.Threading.Tasks.Task`1:InnerInvoke <0x0009d>
          at System.Threading.Tasks.Task:Execute <0x0004b>
          at System.Threading.Tasks.Task:ExecutionContextCallback <0x0007a>
          at System.Threading.ExecutionContext:RunInternal <0x0023e>
          at System.Threading.ExecutionContext:Run <0x0005a>
          at System.Threading.Tasks.Task:ExecuteWithThreadLocal <0x0014a>
          at System.Threading.Tasks.Task:ExecuteEntry <0x0010a>
          at System.Threading.Tasks.TaskScheduler:TryExecuteTask <0x00072>
          at CitizenFX.Core.CitizenTaskScheduler:InvokeTryExecuteTask <0x0004a>
          at CitizenFX.Core.CitizenTaskScheduler:Tick <0x0053a>
          at CitizenFX.Core.InternalManager:TriggerEvent <0x00892>
          at CitizenFX.Core.InternalManager:TriggerEvent <0x000d2>
          at CitizenFX.Core.InternalManager:TriggerEvent <0x002e2>
          at CitizenFX.Core.InternalManager:TriggerEvent <0x001a0>
          at CitizenFX.Core.InternalManager:TriggerEvent <0x00092>
          at CitizenFX.Core.MonoScriptRuntime:TriggerEvent <0x000a2>
          at CitizenFX.Core.IScriptEventRuntime:TriggerEvent <0x0008b>
          at CitizenFX.Core.IScriptEventRuntime:TriggerEvent <0x00132>
=================================================================


================================================================
FXServer crashed.
A dump can be found at 8978\crashes\8f70a2a7-29dd-482a-8f42-71ecaf4774ef.dmp.
In addition to this, a full dump file has been generated at 8978\crashes\8f70a2a7-29dd-482a-8f42-71ecaf4774ef-full.dmp.

Crash report ID: 7891bbe8-5bc4-4810-8df8-d3ab10e1ff29
=================================================================
```

### PR DESCRIPTION
**Pull request by manups4e**
This PR introduces several important improvements and fixes to the MsgPack serialization library:

- Added support for delegates serialization (fixes https://github.com/citizenfx/fivem/issues/2653, https://github.com/citizenfx/fivem/issues/2590, https://github.com/citizenfx/fivem/issues/2582).
- Fixed serialization issues with Lists, ensuring correct handling of collections.
- Corrected string serialization when the string length exceeds 256 bytes (fixes https://github.com/citizenfx/fivem/issues/2613).
- Improved handling of special cases for byte[] and List<byte>, treating them appropriately as binary data (fixes https://github.com/citizenfx/fivem/issues/2571).
- Fixed naming conventions to avoid unsupported characters such as <>.

These changes enhance the robustness and compatibility of the MsgPack formatter, especially when working with complex data types.

### CODE REVIEW

File: MsgPack/MsgPackSerializer.cs [hunk 1]
```diff
@@ -226,11 +255,93 @@ public unsafe void Serialize(CString v)
...
+
+                                    packer.PackArrayHeader(list.Count);
+                                    for (int i = 0; i < list.Count; ++i)
+                                    {
+                                        Serialize(list[i], packer);
+                                    }
+                                }
+                                return;
+                        }
+                    } */
```
Comment (FabianTerhorst) [inline MsgPack/MsgPackSerializer.cs]: Remove the commented out code when its no longer needed.

File: MsgPack/MsgPackSerializer.cs [hunk 2]
```diff
@@ -105,7 +106,23 @@ public void Serialize(short v)
...
 		}
 
-		public void Serialize(ushort v)
+        public void Serialize(Delegate d)
+		{
+            // this works only if msgpack lib is built within fivem, it's not really elegant imho
+            // but it works, so let's not break it now, shall we?
+            // TODO: Make this work without depending from ReferenceFunctionManager
+			// and make our own Canonicalization of the reference id
+			// TODO: Add support for byte 10 (Remote Delegate)? don't think it's enabled in FiveM currently
```
Comment (FabianTerhorst) [inline MsgPack/MsgPackSerializer.cs]: What about the todos here?

Comment (manups4e) [reply MsgPack/MsgPackSerializer.cs]: - At the moment msgpack delegate serialization depends on ReferenceFunctionManager which is not in msgpack repository but when linked in FiveM's project builds and works correctly.
~~Second todo i wanted to ask if i need to also add code 10 or if code 11 is enough for delegate serialization.
as far as i tested code 11 works fine without the need of adding code 10 in the remote delege preprocessor symbols~~

Comment (FabianTerhorst) [reply MsgPack/MsgPackSerializer.cs]: As long as it builds inside the submodule together inside the fivem folder its fine 👍

**Comment by FabianTerhorst** [comment]
@prikolium-cfx When we merge this we can move https://github.com/citizenfx/fivem/pull/3409 to a feature branch.

**Review by prikolium-cfx — APPROVED** [review]

**Comment by prikolium-cfx** [comment]
Thank you for the contribution.
Looks like unit tests failed on build. Could you check what's wrong with that?

**Comment by manups4e** [comment]
Thanks for your quick review and reply 😊 yes build fails due to the delegate serialization method wich depends on ReferenceFunctionManager it doesn't exists in the project but builds correctly when used as a module inside FiveM projects.

https://github.com/citizenfx/msgpack-cs/pull/2#discussion_r2097872202

This is what @FabianTerhorst replied in the matter

**Comment by manups4e** [comment]
In case I can look for an alternative method to serialize delegates to make the library project build unattached from FiveM projects

File: MsgPack/Formatters/ArrayFormatter.cs [hunk 3]
```diff
@@ -7,228 +7,235 @@
...
-			// return null
-			g.MarkLabel(nilWrite);
-			g.Emit(OpCodes.Ldnull);
-			g.Emit(OpCodes.Ret);
-
-			return methodDeserialize;
-		}
-	}
-}
+    internal static class ArrayFormatter
```
Comment (Mathu-lmn) [inline MsgPack/Formatters/ArrayFormatter.cs:10]: Nit : might be worth keeping the same tab indent everywhere so changes can be seen easily ?

**Comment by manups4e** [comment]
Hi i added __Callback Injection__ via Delegate to the Delegate Serializer (sorry for the double Delegate in sentence)
This fixes module building by injecting the `Create` method in `ReferenceFunctionManager` in runtime and not directly by code generating that NullReferenceException on singular build.
A delegation of `MsgPackReferenceRegistrar.CreateFunc` is still required to allow the correct function of the method.
A linked commit has been added in [PR #3409](https://github.com/citizenfx/fivem/pull/3409) to allow method injection (tested and working)
PS.: `REMOTE_FUNCTION_ENABLED` symbol will still require the library to be loaded into fivem project to build atm
